name: Push to Azure container Registry


on: push
    

env:
    image_name: nginx-Fouad

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image     
        run: docker build -t ${{vars.SERVER}}/${{env.image_name}}:latest


      
      - name: Log in to Azure Container Registry
        run: |
            echo "${{Secrets.PASSWORD}}" | docker login ${{vars.SERVER}} -u ${{vars.USER_NAME}} --password-stdin


      - name: push docker image
        run: docker push ${{ vars.SERVER}}/${{env.image_name}}:latest
